name:
    model_name: "vgg16_pretrained_false"
    save_model_filename: 'vgg16_pretrained_false_Run49.pth'
    save_parameters_file: 'vgg16_pretrained_false_Run49'

preprocess:
    seed: 4
    test_size: 0.2

train:
    learning_rate: 0.0001
    weight_decay: 0.002
    num_epochs: 20
    batch_size: 50
