name:
    model_name: "cnn_4layers_custom"
    save_model_filename: 'cnn_4layers_results_Run0.pth'
    save_parameters_file: 'cnn_4layers_results_Run0'

preprocess:
    seed: 4
    test_size: 0.2

train:
    learning_rate: 0.01
    weight_decay: 0.002
    num_epochs: 20
    batch_size: 50
